/**
 * Created by Pasin Suriyentrakorn on 8/25/15.
 * Copyright (c) 2015 Couchbase, Inc All rights reserved.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_couchbase_lite_support_security_SymmetricKey */

#ifndef _Included_com_couchbase_lite_support_security_SymmetricKey
#define _Included_com_couchbase_lite_support_security_SymmetricKey
#ifdef __cplusplus
extern "C" {
#endif
#undef com_couchbase_lite_support_security_SymmetricKey_KEY_SIZE
#define com_couchbase_lite_support_security_SymmetricKey_KEY_SIZE 32L
#undef com_couchbase_lite_support_security_SymmetricKey_MIN_KEY_ROUNDS
#define com_couchbase_lite_support_security_SymmetricKey_MIN_KEY_ROUNDS 200L
#undef com_couchbase_lite_support_security_SymmetricKey_DEFAULT_KEY_ROUNDS
#define com_couchbase_lite_support_security_SymmetricKey_DEFAULT_KEY_ROUNDS 1024L
#undef com_couchbase_lite_support_security_SymmetricKey_MIN_KEY_SALT_SIZE
#define com_couchbase_lite_support_security_SymmetricKey_MIN_KEY_SALT_SIZE 4L
#undef com_couchbase_lite_support_security_SymmetricKey_BLOCK_SIZE
#define com_couchbase_lite_support_security_SymmetricKey_BLOCK_SIZE 16L
#undef com_couchbase_lite_support_security_SymmetricKey_IV_SIZE
#define com_couchbase_lite_support_security_SymmetricKey_IV_SIZE 16L
/*
 * Class:     com_couchbase_lite_support_security_SymmetricKey
 * Method:    nativeDeriveKey
 * Signature: (Ljava/lang/String;[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_couchbase_lite_support_security_SymmetricKey_nativeDeriveKey
  (JNIEnv *, jclass, jstring, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
